UDP_IP_CPP: "192.168.19.1" # LUIGI IP Address
MY_IP: "0.0.0.0" # MY IP Address
UDP_IP_JS: "0.0.0.0" # JAVASCRIPT IP Address

UDP_RECEIVE_PORT_CPP: 65305
UDP_SEND_PORT_CPP: 65306

UDP_RECEIVE_PORT_JS: 65300
UDP_SEND_PORT_JS: 65301

command_offset: 10

debug: True

MAX_OBSTACLES: 6

# 1B Comando corpo
# 1B Comanda testa
# 1B Strategia
# 8B [pos_x, pos_y]
command_format: "<BBBff" 

# 0)      1 double di qualcosa
# 1)      4B header
# 2)      1B versione
# 3)      1B playerNum
# 4)      1B teamNum
# 5)      1B fallen
# 6-9)    3f (12B) [posX, posY, theta]
# 9)      1f (4B) ballAge
# 10-12)  2f (8B) [ballPosX, ballPosY]
# 12)     1B playerRole
# 13)     1B numOfDataBytes
# 14)     1B currentObsSize
# 15-21)  6B obstacleTypes  
# 21)     1B padding
# 22-24)  2B padding
# 24-30)  6f (12B) obsCenterX
# 30-36)  6f (12B) obsCenterY
# 36-42)  6f (12B) obsLastSeen
# 42)     1H (2B) messageBudget
# 43)     1H (2B) secsRemaining
# 44-46)     2B armContact
# 46-48)     2B armPushDirection
# 48-50)     2f (8B) armTimeOfLastContact
data_format: "<d4sBBBB3ff2fBBB6BB2B6f6f6fHH2B2B2f"