# IP Addresses
robot_ip: "10.0.19.28"          # LUIGI IP Address
local_ip: "0.0.0.0"             # My IP Address
my_ip: "10.0.255.230"

# Ports
debug_receive_port: 65305
debug_send_port: 65301

upper_image_receive_port: 5432
lower_image_receive_port: 5431

command_send_port: 65306
command_receive_port: 65300

# Command Offset
command_offset: 10

# Debug Mode
debug: true

# Maximum Number of Obstacles
max_obstacles: 20

# Command Format
# 1B: Command body
# 1B: Command head
# 1B: Strategy
# 8B: [pos_x, pos_y]
command_format: "<BBBff"

# Data Format
# 0)      1 double of something
# 1)      4B header
# 2)      1B version
# 3)      1B player_num
# 4)      1B team_num
# 5)      1B fallen
# 6-9)    3f (12B) [pos_x, pos_y, theta]
# 9)      1f (4B) ball_age
# 10-12)  2f (8B) [ball_pos_x, ball_pos_y]
# 12)     1H (2B) num_of_data_bytes
# 13)     1B player_role
# 14)     1B current_obs_size
# 15-35)  20B obstacle_types  
# 35-55)  20f (80B) obs_center_x
# 55-75)  20f (80B) obs_center_y
# 75-95)  20f (80B) obs_last_seen
# 95)     1H (2B) message_budget
# 96)     1H (2B) secs_remaining
# 97-99)  2B arm_contact
# 99-101) 2B arm_push_direction
# 101-103)2f (8B) arm_time_of_last_contact
# 103)    2f (8B) padding (whistle)
# 104-106) 2f (8B) teamball
# 106-108) 2f (8B) teamballvel
# 108)    12B padding

data_format: "<d4sBBBB3ff2fHBB20B20f20f20fHH2B2B2f2f2f2f12B"

# Image Size
upper_image_width: 640
upper_image_height: 480
lower_image_width: 320
lower_image_height: 240